# Deploy to Firebase Hosting on push to main
name: Deploy to Firebase Hosting on main push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      
      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SINUSANMARTINSEDEPASTO_C87ED }}
          channelId: live
          projectId: sinusanmartinsedepasto-c87ed
